version: "3.8"

services:
  waha:
    image: devlikeapro/waha:latest
    restart: always
    environment:
      WHATSAPP_HOOK_URL: http://n8n:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3000:3000"

  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      WEBHOOK_URL: http://72.62.11.29:5678
      N8N_HOST: 72.62.11.29
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
      N8N_SECURE_COOKIE: "false"   # só até você ter HTTPS
      GENERIC_TIMEZONE: America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"

volumes:
  waha_sessions:
  waha_media:
  n8n_data:
